### ISSUE TITLE
bias correction for mes.m

### ISSUE THREAD

**Issue by rduesing** [hhentschke/measures-of-effect-size-toolbox#1]
I would like to pick up the issue with the Hedge's g bias correction I originally started on MATLAB File Exchange.

**My original post:**

> Maybe I am mistaken, but it seems as if your bias correction in mes.m is not correct for dependent data. You comment:
> 
> % correct for bias due to small n (both dependent and independent
> % data, Kline 2004 (p. 102, 106); Nakagawa & Cuthill 2007)
> biasFac=(1-(3./(4 * n1+4 * n2-9)));
> es=es. * biasFac;
> 
> But this is not the case, the general form is j = 1 - (3/(4 * df - 1)), where df are the degrees of freedom. In case of independent data it is df=(n1+n2-2) [then j=biasFac=(1-(3./(4 * n1+4 * n2-9)))], but for the dependent data case df=npairs-1, where npairs=n1=n2 (Borenstein, 2009; Kline, 2004, 2013; Rosenthal, 1994, and also Nakagawa & Cuthill, but they only explain it in the text).

**Your answer:**

>  I see your point, but according to Nakagawa and Cuthill (2007), "...note that when a paired designed is used, n 1 = n 2 = n so that the denominator can be written as 8(n–1) – 1..." (p. 599), which is the current implementation. That's about the only reference to bias correction for Hedges' g in the case of dependent data I have found so far. Please let me know (see above) if I'm mistaken or there are other grounds for changing the code. 

So maybe I explain my point in greater detail and why I think that the formula in mes.m is only valid for independent data. According to Borenstein (2009, p. 226) and Kline (2012, p.134), the general correction factor depends on the degrees of freedom and not directly the sample size. This is an important point in my opinion, because from this point of view, the issue gets more apparent. Both calculate the correction factor (J(df) or c(df), respectively) 1 - (3/(4 * df - 1)). The crucial point is that the calculation of the df for the independent and the dependent case is NOT the same. For the independent case it is df=n1+n2-2, but for the dependent case it is df=n-1.
Your script uses for both cases the formula 4 * n1+4 * n2-9, which is a reformulation of the independent case (as well as 8(n-1)-1 in Nakagawa & Cuthill).

You_ can find a detailed example for both cases in Borenstein (2009). Here the independent example has n1=50 and n2=50, the dependent sample n=50. According to your script, the correction factor would be the same for both cases. Borenstein calculates J(50+50-2)=1 - (3/(4 * 98 - 1))=0.9923 for the independent case and for the dependent J(50-1)=1 - (3/(4 * 49 - 1))=0.9846.

Although Kline does not give an explicit example for the dependent case, he provides the general df based formula as already mentioned. Therefore, it may be concluded that this would also hold for the dependent case.

**Edit:** The Borenstein chapter appears in the book _The handbook of research synthesis and meta-analysis, 2nd ed._ which is edited by L.V. Hedges himself amongst others. For me, this seems to be a good indicator that the correction factor for the dependent case provided by Borenstein is correct.

Ref.:
Borenstein, M., (2009). Effect sizes for continuous data. In H. Cooper, L.V. Hedges, and J.C. Valentine, The handbook of research synthesis and meta-analysis, 2, 221-235.
Kline, R. (2012). Beyond significance testing. Washington, DC: American Psychological Association.

**Comment by hhentschke** [comment]
First of all, sorry for the long delay in my reply (vacation time :)).

I took a deep look at both Borenstein (2009) and again Kline (2012) and Nakagawa & Cuthill (Nakagawa,S. and Cuthill,I.C.; Biological Reviews 82:591-605, 2007) to resolve the issue (forgive me for omitting the year in the citations from now on). Doing so, I realized that two philosophies of computing Hedges' g (abbreviated g from now on) seem to coexist in the literature, and we need to examine these when dealing with bias correction. To support the discussion with concrete numbers, let's generate a simple artificial dataset supposedly representing matched (dependent) data, namely two groups of random integers with a strong correlation:

x=[15    18    11    14    12    11    12    14    14    16]
y=[12    13     9     8    11     6     9    10    13    14]

which I generated in Matlab R2017a via 

rng(1);
x=randi(10,10,1);
y=x+randi(6,10,1);
x'
y'
plot(x,y,'o')
corr(x,y)

PHILOSOPHY 1: 
Compute Hedges'g in the same fashion as for independent designs to allow for better comparability across studies. This view is exposed by Kline on pages 105-106 and Nakagawa and Cuthill (p. 595, '... notice that d calculations do not change according to whether or not the two groups or treatments are independent, whereas t calculations do') and has thus far also been adhered to in the MES toolbox. In mes.m, different formulae for the computation of g are imlemented, but these result in the same numerical results (within machine precision) and exist solely for efficiency reasons (in the dependent case, we don't compute variable sP by default, that's why the code employs formula 4.11 in Kline, making use of the t statistic for dependent groups, which is in any case precomputed):

stats_dep=mes(x,y,'hedgesg','isDep',true)
stats_indep=mes(x,y,'hedgesg','isDep',false)
isequal(stats_dep.hedgesg,stats_indep.hedgesg)

In the current implementation of mes.m, the values for g in both cases (namely, 1.27) get multiplied by the same bias correction factor, so even without it they are identical. So, given that computations and g values are identical in the dependent and independent case, it doesn't make sense to apply different bias correction factors. That had been my argument so far. 
On the occasion, two points: first, we can verify that the uncorrected g is indeed positively biased with a simple simulation:

sd=1;
m1=1;
m2=0; 

% number of samples per group
n=10;
% number of test cases (must be in the dozens of thousands, otherwise this will be pointless)
nTest=20000;
hedgesg=nan(nTest,1);

% seed for random number generator
rng(0);
% generate uncorrelated data sets
X=randn(n,nTest)*sd+m1;
Y=randn(n,nTest)*sd+m2;

parfor k=1:nTest
  stats=mes(X(:,k),Y(:,k),'hedgesg','isDep',0);
  hedgesg(k)=stats.hedgesg;
end

mean(hedgesg)

With the currently implemented bias correction, the mean value of g resulting from the code snippet above is 1.0004, whereas the uncorrected value is 1.0445, further away from the expected value of exactly 1. This tiny difference leads to the second point: as Borenstein argued, the bias correction factor is very close to unity for all but the smallest sample sizes and thus in practice mostly irrelevant; e.g. for n1=n2=10 as above it is ~0.95 (formula for independent groups).



PHILOSOPHY 2:
Compute g differently in the dependent case, because 'the natural unit of deviation is the standard deviation of the difference score' (Borenstein). This approach, also presented in Nakagawa & Cuthill alongside the first approach (cf. formulas 1 and 3 vs. 4 in Table 1), factors in the correlation between the two groups. Please note that in this approach, the correlation '...is known or can be estimated with high precision. Often, the researcher will need to use data from other sources to estimate this correlation' (Borenstein). In other words, the values of g depend on our estimate of r. In real life, I assume that most scientists will not bother or have no means to extract the best value of that correlation from other sources but instead estimate it from the sample at hand (as Borenstein does in the example computation). Anyways, implementing Borenstein's formulae 12.19-12.22 and running it on the integer groups x and y above yields g=1.31 (uncorrected) and 1.20 (corrected, with df=n=10). The same uncorrected value will be obtained with eq. 4 in Table 1 in Nakagawa & Cuthill. So, in this approch for dependent data, the values of both g and the bias correction factor differ.

My conclusions:

1. Both approaches yield somewhat different results, and it is a matter of deliberate choice (or taste) which philosophy of computing g for dependent data we want to pursue
2. If we follow the second (Borenstein's) approach, the bias correction factor must in fact be computed using df=n (number of matched pairs)-1; in the first approach I believe the current implementation is correct, see above.

The question is whether Borenstein's approach should be implemented in mes.m (which I obviously did already in my local version; I'd be happy to do this).

Would be thankful for comments!

**Comment by rduesing** [comment]
Dear Harald, 

many thanks for your in depth answer, I really appreciate it. And I agree with you that there are two different philosophies for the calculation of d/g in the dependent sample case. For the sake of clarity, I will use the nomenclature from Lakens (2013), because it makes it easier to distinguish between the different effect size measures. First of all, a comparison of the different measures and names (formula numbering of the specific publication in parentheses)

**Independent measures**

•	Lakens Cohen’s d_s (1)= Kline’s d_pool for dependent cases (5.3) = Cumming’s d (11.6) = Borenstein’s d (12.11) = Nakagawa & Cuthill (1;3)
•	Lakens Hedges’ g_s (4)= Kline’s d_pool * c(df) (5.6) = Cumming’s d_unb (11.13) = Borenstein’s d*J (12.15)

**Dependent measures**

•	Lakens Cohen’s d_z (6 & 7) = Kline’s d_diff (5.7) = Cumming’s d_diff (11.12)
•	Lakens Cohen’s d_rm (9) = Borenstein’s d (12.19) = Nakagawa & Cuthill (4)
•	Lakens Cohen’s d_av (10; denominator in formula not correct) = Kline’s d_pool dependent case (5.5) = Cumming’s d with s_av as denominator (p. 292) and formula 8.4 in Cumming and Calin-Jageman

The different philosophies you mention are the difference between d_rm and d_av, using different standardizer, which will lead to different interpretations of the d value. Whereas d_rm uses the standard deviation of the difference scores, d_av uses an averaged SD score of the two SD measures. So, d_rm is in difference score units and d_av in original units. So far so good and I think there is much agreement that in most cases d_av is preferable (Kline; Cumming; Cumming and Calin-Jageman). But this does not clarify how to correct for bias. My intention with the Borenstein example was not to distinguish between these two measures, but to show that the correction factor depends on the degrees of freedom. So the main question remains “how to correct for bias in case of dependent samples, either for d_rm or d_av?”.

You cited one premise from Nakagawa and Cuthill “notice that d calculations do not change according to whether or not the two groups or treatments are independent, whereas t calculations do”. I would also totally agree with it. If you calculate the effect sizes from your example you will see that Cohen’s d_s (independent) and Cohen’s d_av (dependent) will lead to the same result 1.3275. So it is also not surprising that both of your g calculations lead to the same result, since you used Nakagawa & Cuthill’s formula 1 (=d_s) for the independent case and Kline’s formula 5.7 (=d_av) for the dependent case. If you now use the same correction factor for both cases, it has to be the same result, as shown in

stats_dep=mes(x,y,'hedgesg','isDep',true)
stats_indep=mes(x,y,'hedgesg','isDep',false)
isequal(stats_dep.hedgesg,stats_indep.hedgesg)

But I do not agree with your conclusion you draw from it. I think your argument that both calculations lead to the same result and therefore both approaches should have the same correction factor is not plausible. I would argue the other way around, because the effect size calculation is identical, you should accommodate the dependence in the correction factor. To my knowledge, Nakagawa and Cuthill are the only ones who use the same correction for dependent and independent samples. Kline is not very explicit, but only provides a general correction formula based on degrees of freedom. Cumming gives also a general correction factor, but since he refers always on d for dependent and independent samples and gives only a general correction factor, again based on degrees of freedom, it seems obvious that different corrections have to be applied. Additionally, in his ESCI program, the correction of d_av is also df based. Lakens also applied the df based correction in his Excel spreadsheet.

Another reason why I believe that the correction should be done based on df is the original work by Hedges (1981) himself. Although, he does not provide an example for the dependent case, he discusses two different cases of independent samples, i.e. Glass delta with only the control group standard deviation as denominator (formula 2) or the pooled standard deviation (4; which is equal to d_s). He shows that the distributions of both effect size estimators are different, since they rely on the non-central t-distribution, which in turn depends on the degrees of freedom. I don’t see an argument, why for d_rm or d_av this logic should not apply.

References
Borenstein, M. (2009). Effect sizes for continuous data. The handbook of research synthesis and meta-analysis, 2, 221-235.
Cumming, G. (2013). Understanding the new statistics: Effect sizes, confidence intervals, and meta-analysis. Routledge.
Cumming, G., & Calin-Jageman, R. (2016). Introduction to the new statistics: Estimation, open science, and beyond. Routledge.
Hedges, L. V. (1981). Distribution theory for Glass's estimator of effect size and related estimators. Journal of educational statistics, 6(2), 107-128.
Kline, R. (2012). Beyond significance testing. Washington, DC: American Psychological Association.
Lakens, D. (2013). Calculating and reporting effect sizes to facilitate cumulative science: a practical primer for t-tests and ANOVAs. Frontiers in psychology, 4.
Nakagawa, S., & Cuthill, I. C. (2007). Effect size, confidence interval and statistical significance: a practical guide for biologists. Biological reviews, 82(4), 591-605.

**Comment by hhentschke** [comment]
Dear Rainer, 

I think you are right about the bias correction, at least that is what I gather from the majority of publications you listed; Nakagawa & Cuthill seem to be the outlier here. I'm working on a revised and extended version of mes.m which incorporates the correct bias correction and more variants of Hedges'g/Cohen's d for dependent data. Should be done in a few days.

**Comment by hhentschke** [comment]
So...a lot of time has passed, and it seems we have found a good solution, namely using an alternative bias correction proposed by Bonett (2015), which is explained in detail in the documentation of the latest commit. I'd also like to point to simulation code specifically designed to clarify this and other issues (best coverage of confidence intervals):
https://github.com/hhentschke/simulate-standardized-mean-differences
