### ISSUE TITLE
r equivalent for 2 continuous variables

### ISSUE THREAD

**Issue by zits69** [hhentschke/measures-of-effect-size-toolbox#3]
Hi

Thank you so much for sharing this very helpful toolbox!

I've been through the documentation, and I can't seem to find a measure for running a correlation between 2 continuous/metric variables - it seems that most are related to either ordinal or dichotomous variables.

Could you please point me to the right function? I used fast_corr but I am not certain that this isn't just a Pearson's and if it's relevant to datasets with over 10,000 data points (analysing large dataset collected online). I did use 'mes' with 'requiv' as in the documentation, but just checking that it's OK for 2 metric variables.

Thanks in advance for your help
z

**Comment by hhentschke** [comment]
I think you are confusing two things. 

First, the question you're trying to answer. Is it a) 'How does variable A correlate with variable B ?' For example, how does age relate to income in company X? Or rather b) 'To what degree does variable A differ in two different conditions?' (e.g. how strongly does income differ between young (18-30) and seasoned (50+) employees of that company?). 

If it is question (a), Pearson correlation (and similar) is what you want. For this, you have, in pure Matlab, functions corr, xcorr, corrcoef. fast_corr, by Elliot Layden, is a fast vectorized variant designed for multi-column data. You don't need our toolbox for that.

If it is question (b), our toolbox may be handy; you could use one of the many measures of effect size (mes) designed for two variables, including those which are termed 'XY correlation', for example point biserial correlation. Please read the  paragraph "The 'correlation' type of analyses" in the docs for further elaboration.  

The second issue is that of the scale (metric vs ordinal). For both problem types (a) and (b) there are analyses appropriate for metric and ordinal data. In the case of (b), you could use point biserial correlation or in fact most of the other mes in our toolbox, because most of them are in fact suitable for metric data (contrary to your impression). For ordinal data, e.g. rank biserial correlation is appropriate, but also e.g. Cohen's U3.
